### ISSUE TITLE
CheckinEvent doens't seem to populate 'CommitterDisplay' property

### ISSUE THREAD

**Issue by worldspawn** [timclipsham/tfs-hipchat#5]
On TFS 2010 at least I am now getting messages (after i got ur new source) like.

checked in changeset 4101 (Solar.Mercury)
Merged from Main

**Comment by timclipsham** [comment]
Interesting… that's an issue. It's because I'm using "CommiterDisplay" rather than "Committer".

Using TFS 2012 it shows the display name of the user:
Committer = "DOMAIN\john.smith"
CommitterDisplay = "John Smith"

Maybe TFS 2010 doesn't support CommitterDisplay?

The CommitterDisplay format is preferable because it's easier to read, so we can change it to prefer CommitterDisplay and if it has no meaningful value fallback to Committer.

**Comment by worldspawn** [comment]
something like?

``` csharp
public string CommitterDisplay
{
        get { return _committerDisplay ?? Committer; }
        set { _committerDisplay = value; }
}
```

Ok I _was_ getting DOMAIN\user.name so that all makes sense.

**Comment by timclipsham** [comment]
Yep something like that :)

Eventually I'd like to add some smarts to detect DOMAIN\user.name and
format it nicely (especially for the build events as they don't contain a
display name at all) because it is such a common pattern, but what you've
suggested will fix the issue for now.

Sent from my iPhone

On 19/02/2013, at 4:51 PM, Sam Critchley notifications@github.com wrote:

something like?

public string CommitterDisplay
        {
            get { return _committerDisplay ?? Committer; }
            set { _committerDisplay = value; }
        }

Ok I _was_ getting DOMAIN\user.name so that all makes sense.

—
Reply to this email directly or view it on
GitHubhttps://github.com/timclipsham/tfs-hipchat/issues/5#issuecomment-13758054.

**Comment by worldspawn** [comment]
Actually it might be more appropriate to have the notifier do the coalesce op in the String.Format rather than futzing with the event class.

**Comment by timclipsham** [comment]
Good point, that makes more sense.

Sent from my iPhone

On 20/02/2013, at 7:59 PM, Sam Critchley notifications@github.com wrote:

Actually it might be more appropriate to have the notifier do the coalesce
op in the String.Format rather than futzing with the event class.

—
Reply to this email directly or view it on
GitHubhttps://github.com/timclipsham/tfs-hipchat/issues/5#issuecomment-13824011.

**Comment by timclipsham** [comment]
Decided to add a method to the CheckinEvent object. Was easier to write tests for it there as well.
