### ISSUE TITLE
xUnit compatibility failures past version 1.9.1

### ISSUE THREAD

**Issue by dambrisco** [timclipsham/tfs-hipchat#6]
This isn't directly an issue with this project, but when pulling the project, if the Nuget references fail to be pulled down correctly and you're forced to update them yourself, xUnit will fail to install directly from the Package Manager.

(For some reason, three out of three times I was unable to pull down this project and build directly. This appeared to be related to Visual Studio incorrectly believing a "nugets.exe" file to exist.)

To install a functioning version of xUnit, you'll need to go back to at least 1.9.1 and can do so by entering `Install-Package xunit -Version 1.9.1` into the Package Manager Console after selecting TfsHipChat.Tests as your default project.

**Comment by timclipsham** [comment]
Thanks for raising this.

I discovered the .gitignore file prevented `.nuget/NuGet.exe` from being committed (by the *.exe rule). Since that rule is a recommended Visual Studio default, I chose to re-enable NuGet Package Restore and force add `.nuget/NuGet.exe`.

Let me know if that doesn't fix the issue you had.

**Comment by dambrisco** [comment]
Confirming that the applied fix works. Solution can be built OOTB now.
